using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace API.Migrations
{
    public partial class AddFlightDisruptionDecisions : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "FlightDisruptionDecisions" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "BookingId" integer NOT NULL,
                    "UserId" integer NOT NULL,
                    "AffectedFlightId" integer NOT NULL,
                    "LegType" integer NOT NULL DEFAULT 0,
                    "Status" integer NOT NULL DEFAULT 0,
                    "DecisionType" integer NOT NULL DEFAULT 0,
                    "DecisionDeadline" timestamp with time zone NOT NULL,
                    "DecidedAt" timestamp with time zone NULL,
                    "NewFlightId" integer NULL,
                    "Reason" character varying(500) NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NOT NULL,
                    "IsDeleted" boolean NOT NULL DEFAULT FALSE,
                    "DeletedAt" timestamp with time zone NULL,
                    "Version" integer NOT NULL DEFAULT 0
                );

                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint
                        WHERE conname = 'FK_FlightDisruptionDecisions_Bookings_BookingId'
                    ) THEN
                        ALTER TABLE "FlightDisruptionDecisions"
                            ADD CONSTRAINT "FK_FlightDisruptionDecisions_Bookings_BookingId"
                            FOREIGN KEY ("BookingId") REFERENCES "Bookings" ("Id") ON DELETE CASCADE;
                    END IF;

                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint
                        WHERE conname = 'FK_FlightDisruptionDecisions_Users_UserId'
                    ) THEN
                        ALTER TABLE "FlightDisruptionDecisions"
                            ADD CONSTRAINT "FK_FlightDisruptionDecisions_Users_UserId"
                            FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;
                    END IF;

                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint
                        WHERE conname = 'FK_FlightDisruptionDecisions_Flights_AffectedFlightId'
                    ) THEN
                        ALTER TABLE "FlightDisruptionDecisions"
                            ADD CONSTRAINT "FK_FlightDisruptionDecisions_Flights_AffectedFlightId"
                            FOREIGN KEY ("AffectedFlightId") REFERENCES "Flights" ("Id") ON DELETE RESTRICT;
                    END IF;

                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint
                        WHERE conname = 'FK_FlightDisruptionDecisions_Flights_NewFlightId'
                    ) THEN
                        ALTER TABLE "FlightDisruptionDecisions"
                            ADD CONSTRAINT "FK_FlightDisruptionDecisions_Flights_NewFlightId"
                            FOREIGN KEY ("NewFlightId") REFERENCES "Flights" ("Id") ON DELETE RESTRICT;
                    END IF;
                END $$;

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_FlightDisruptionDecisions_BookingId_AffectedFlightId_LegType"
                ON "FlightDisruptionDecisions" ("BookingId", "AffectedFlightId", "LegType");

                CREATE INDEX IF NOT EXISTS "IX_FlightDisruptionDecisions_UserId_Status"
                ON "FlightDisruptionDecisions" ("UserId", "Status");

                CREATE INDEX IF NOT EXISTS "IX_FlightDisruptionDecisions_DecisionDeadline"
                ON "FlightDisruptionDecisions" ("DecisionDeadline");
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS "FlightDisruptionDecisions";
                """);
        }
    }
}
