using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Migrations
{
    public partial class AddBookingLegsAndLegPassengers : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TABLE "BookingServices" ADD COLUMN IF NOT EXISTS "BookingLegPassengerId" integer NULL;

                CREATE TABLE IF NOT EXISTS "BookingLegs" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "BookingId" integer NOT NULL,
                    "FlightId" integer NOT NULL,
                    "SeatClassId" integer NOT NULL,
                    "LegType" integer NOT NULL DEFAULT 0,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NOT NULL,
                    "IsDeleted" boolean NOT NULL DEFAULT false,
                    "DeletedAt" timestamp with time zone NULL,
                    "Version" integer NOT NULL DEFAULT 0
                );

                CREATE TABLE IF NOT EXISTS "BookingLegPassengers" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "BookingLegId" integer NOT NULL,
                    "BookingPassengerId" integer NOT NULL,
                    "FlightSeatInventoryId" integer NOT NULL,
                    "DocumentCheckStatus" integer NOT NULL DEFAULT 1,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NOT NULL,
                    "IsDeleted" boolean NOT NULL DEFAULT false,
                    "DeletedAt" timestamp with time zone NULL,
                    "Version" integer NOT NULL DEFAULT 0
                );

                CREATE INDEX IF NOT EXISTS "IX_BookingServices_BookingLegPassengerId"
                ON "BookingServices" ("BookingLegPassengerId");
                CREATE INDEX IF NOT EXISTS "IX_BookingLegs_BookingId" ON "BookingLegs" ("BookingId");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_BookingLegs_BookingId_LegType" ON "BookingLegs" ("BookingId", "LegType");
                CREATE INDEX IF NOT EXISTS "IX_BookingLegs_FlightId" ON "BookingLegs" ("FlightId");
                CREATE INDEX IF NOT EXISTS "IX_BookingLegs_SeatClassId" ON "BookingLegs" ("SeatClassId");
                CREATE INDEX IF NOT EXISTS "IX_BookingLegPassengers_BookingLegId" ON "BookingLegPassengers" ("BookingLegId");
                CREATE INDEX IF NOT EXISTS "IX_BookingLegPassengers_BookingPassengerId" ON "BookingLegPassengers" ("BookingPassengerId");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_BookingLegPassengers_BookingLegId_BookingPassengerId" ON "BookingLegPassengers" ("BookingLegId", "BookingPassengerId");
                CREATE INDEX IF NOT EXISTS "IX_BookingLegPassengers_FlightSeatInventoryId" ON "BookingLegPassengers" ("FlightSeatInventoryId");

                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_BookingLegs_Bookings_BookingId') THEN
                        ALTER TABLE "BookingLegs"
                        ADD CONSTRAINT "FK_BookingLegs_Bookings_BookingId"
                        FOREIGN KEY ("BookingId") REFERENCES "Bookings"("Id") ON DELETE CASCADE;
                    END IF;

                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_BookingLegs_Flights_FlightId') THEN
                        ALTER TABLE "BookingLegs"
                        ADD CONSTRAINT "FK_BookingLegs_Flights_FlightId"
                        FOREIGN KEY ("FlightId") REFERENCES "Flights"("Id") ON DELETE RESTRICT;
                    END IF;

                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_BookingLegs_SeatClasses_SeatClassId') THEN
                        ALTER TABLE "BookingLegs"
                        ADD CONSTRAINT "FK_BookingLegs_SeatClasses_SeatClassId"
                        FOREIGN KEY ("SeatClassId") REFERENCES "SeatClasses"("Id") ON DELETE RESTRICT;
                    END IF;

                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_BookingLegPassengers_BookingLegs_BookingLegId') THEN
                        ALTER TABLE "BookingLegPassengers"
                        ADD CONSTRAINT "FK_BookingLegPassengers_BookingLegs_BookingLegId"
                        FOREIGN KEY ("BookingLegId") REFERENCES "BookingLegs"("Id") ON DELETE CASCADE;
                    END IF;

                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_BookingLegPassengers_BookingPassengers_BookingPassengerId') THEN
                        ALTER TABLE "BookingLegPassengers"
                        ADD CONSTRAINT "FK_BookingLegPassengers_BookingPassengers_BookingPassengerId"
                        FOREIGN KEY ("BookingPassengerId") REFERENCES "BookingPassengers"("Id") ON DELETE CASCADE;
                    END IF;

                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_BookingLegPassengers_FlightSeatInventories_FlightSeatInventoryId') THEN
                        ALTER TABLE "BookingLegPassengers"
                        ADD CONSTRAINT "FK_BookingLegPassengers_FlightSeatInventories_FlightSeatInventoryId"
                        FOREIGN KEY ("FlightSeatInventoryId") REFERENCES "FlightSeatInventories"("Id") ON DELETE RESTRICT;
                    END IF;

                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_BookingServices_BookingLegPassengers_BookingLegPassengerId') THEN
                        ALTER TABLE "BookingServices"
                        ADD CONSTRAINT "FK_BookingServices_BookingLegPassengers_BookingLegPassengerId"
                        FOREIGN KEY ("BookingLegPassengerId") REFERENCES "BookingLegPassengers"("Id") ON DELETE SET NULL;
                    END IF;
                END $$;
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_BookingServices_BookingLegPassengers_BookingLegPassengerId",
                table: "BookingServices");

            migrationBuilder.DropTable(
                name: "BookingLegPassengers");

            migrationBuilder.DropTable(
                name: "BookingLegs");

            migrationBuilder.DropIndex(
                name: "IX_BookingServices_BookingLegPassengerId",
                table: "BookingServices");

            migrationBuilder.DropColumn(
                name: "BookingLegPassengerId",
                table: "BookingServices");
        }
    }
}
