CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE TABLE "Aircraft" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Model" character varying(100) NOT NULL,
        "RegistrationNumber" character varying(50) NOT NULL,
        "TotalSeats" integer NOT NULL,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_Aircraft" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE TABLE "Airports" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Code" character varying(10) NOT NULL,
        "Name" character varying(255) NOT NULL,
        "City" character varying(100) NOT NULL,
        "Province" character varying(100),
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_Airports" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE TABLE "Promotions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Code" character varying(50) NOT NULL,
        "DiscountType" integer NOT NULL DEFAULT 0,
        "DiscountValue" numeric(10,2) NOT NULL,
        "ValidFrom" timestamp with time zone NOT NULL,
        "ValidTo" timestamp with time zone NOT NULL,
        "UsageLimit" integer,
        "UsedCount" integer NOT NULL DEFAULT 0,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Promotions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE TABLE "Roles" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(50) NOT NULL,
        "Description" character varying(500),
        CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE TABLE "SeatClasses" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Code" character varying(20) NOT NULL,
        "Name" character varying(100) NOT NULL,
        "RefundPercent" numeric(5,2) NOT NULL,
        "ChangeFee" numeric(10,2) NOT NULL,
        "Priority" integer NOT NULL,
        CONSTRAINT "PK_SeatClasses" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE TABLE "Users" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Email" character varying(255) NOT NULL,
        "PasswordHash" text NOT NULL,
        "FullName" character varying(255) NOT NULL,
        "Phone" character varying(20),
        "GoogleId" character varying(255),
        "Status" integer NOT NULL DEFAULT 0,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE TABLE "Routes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "DepartureAirportId" integer NOT NULL,
        "ArrivalAirportId" integer NOT NULL,
        "DistanceKm" integer NOT NULL,
        "EstimatedDurationMinutes" integer NOT NULL,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_Routes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Routes_Airports_ArrivalAirportId" FOREIGN KEY ("ArrivalAirportId") REFERENCES "Airports" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Routes_Airports_DepartureAirportId" FOREIGN KEY ("DepartureAirportId") REFERENCES "Airports" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE TABLE "AircraftSeatTemplates" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "AircraftId" integer NOT NULL,
        "SeatClassId" integer NOT NULL,
        "DefaultSeatCount" integer NOT NULL,
        "DefaultBasePrice" numeric(10,2) NOT NULL,
        CONSTRAINT "PK_AircraftSeatTemplates" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AircraftSeatTemplates_Aircraft_AircraftId" FOREIGN KEY ("AircraftId") REFERENCES "Aircraft" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AircraftSeatTemplates_SeatClasses_SeatClassId" FOREIGN KEY ("SeatClassId") REFERENCES "SeatClasses" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE TABLE "RefundPolicies" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SeatClassId" integer NOT NULL,
        "HoursBeforeDeparture" integer NOT NULL,
        "RefundPercent" numeric(5,2) NOT NULL,
        "PenaltyFee" numeric(10,2) NOT NULL DEFAULT 0.0,
        CONSTRAINT "PK_RefundPolicies" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RefundPolicies_SeatClasses_SeatClassId" FOREIGN KEY ("SeatClassId") REFERENCES "SeatClasses" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE TABLE "AuditLogs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ActorId" integer,
        "Action" character varying(100) NOT NULL,
        "EntityType" character varying(100) NOT NULL,
        "EntityId" integer NOT NULL,
        "BeforeJson" text,
        "AfterJson" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AuditLogs_Users_ActorId" FOREIGN KEY ("ActorId") REFERENCES "Users" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE TABLE "EmailVerificationTokens" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "Code" character varying(500) NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "UsedAt" timestamp with time zone,
        CONSTRAINT "PK_EmailVerificationTokens" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_EmailVerificationTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE TABLE "NotificationLogs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "Email" character varying(255),
        "Type" character varying(50) NOT NULL,
        "Title" character varying(255) NOT NULL,
        "Content" text NOT NULL,
        "Status" integer NOT NULL DEFAULT 0,
        "SentAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_NotificationLogs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_NotificationLogs_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE TABLE "PasswordResetTokens" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "Code" character varying(500) NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "UsedAt" timestamp with time zone,
        CONSTRAINT "PK_PasswordResetTokens" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PasswordResetTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE TABLE "RoleUser" (
        "RolesId" integer NOT NULL,
        "UsersId" integer NOT NULL,
        CONSTRAINT "PK_RoleUser" PRIMARY KEY ("RolesId", "UsersId"),
        CONSTRAINT "FK_RoleUser_Roles_RolesId" FOREIGN KEY ("RolesId") REFERENCES "Roles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_RoleUser_Users_UsersId" FOREIGN KEY ("UsersId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE TABLE "UserRoles" (
        "UserId" integer NOT NULL,
        "RoleId" integer NOT NULL,
        CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_UserRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE TABLE "Flights" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FlightNumber" character varying(20) NOT NULL,
        "RouteId" integer NOT NULL,
        "AircraftId" integer NOT NULL,
        "DepartureTime" timestamp with time zone NOT NULL,
        "ArrivalTime" timestamp with time zone NOT NULL,
        "Status" integer NOT NULL DEFAULT 0,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Flights" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Flights_Aircraft_AircraftId" FOREIGN KEY ("AircraftId") REFERENCES "Aircraft" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Flights_Routes_RouteId" FOREIGN KEY ("RouteId") REFERENCES "Routes" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE TABLE "Bookings" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "BookingCode" character varying(10) NOT NULL,
        "UserId" integer NOT NULL,
        "TripType" integer NOT NULL DEFAULT 0,
        "OutboundFlightId" integer NOT NULL,
        "ReturnFlightId" integer,
        "Status" integer NOT NULL DEFAULT 0,
        "ContactEmail" text NOT NULL,
        "ContactPhone" character varying(20),
        "TotalAmount" numeric(10,2) NOT NULL,
        "DiscountAmount" numeric(10,2) NOT NULL DEFAULT 0.0,
        "FinalAmount" numeric(10,2) NOT NULL,
        "ExpiresAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "PromotionId" integer,
        CONSTRAINT "PK_Bookings" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Bookings_Flights_OutboundFlightId" FOREIGN KEY ("OutboundFlightId") REFERENCES "Flights" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Bookings_Flights_ReturnFlightId" FOREIGN KEY ("ReturnFlightId") REFERENCES "Flights" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Bookings_Promotions_PromotionId" FOREIGN KEY ("PromotionId") REFERENCES "Promotions" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_Bookings_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE TABLE "FlightSeatInventories" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FlightId" integer NOT NULL,
        "SeatClassId" integer NOT NULL,
        "TotalSeats" integer NOT NULL,
        "AvailableSeats" integer NOT NULL,
        "HeldSeats" integer NOT NULL DEFAULT 0,
        "SoldSeats" integer NOT NULL DEFAULT 0,
        "BasePrice" numeric(10,2) NOT NULL,
        "CurrentPrice" numeric(10,2) NOT NULL,
        "Version" integer NOT NULL DEFAULT 0,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_FlightSeatInventories" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FlightSeatInventories_Flights_FlightId" FOREIGN KEY ("FlightId") REFERENCES "Flights" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_FlightSeatInventories_SeatClasses_SeatClassId" FOREIGN KEY ("SeatClassId") REFERENCES "SeatClasses" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE TABLE "Payments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "BookingId" integer NOT NULL,
        "Provider" character varying(50) NOT NULL,
        "Method" character varying(50) NOT NULL,
        "Amount" numeric(10,2) NOT NULL,
        "Status" integer NOT NULL DEFAULT 0,
        "TransactionRef" character varying(255),
        "QrCodeData" text,
        "PaidAt" timestamp with time zone,
        "RawCallbackData" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Payments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Payments_Bookings_BookingId" FOREIGN KEY ("BookingId") REFERENCES "Bookings" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE TABLE "PromotionUsages" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PromotionId" integer NOT NULL,
        "BookingId" integer NOT NULL,
        "DiscountAmount" numeric(10,2) NOT NULL,
        "UsedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_PromotionUsages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PromotionUsages_Bookings_BookingId" FOREIGN KEY ("BookingId") REFERENCES "Bookings" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_PromotionUsages_Promotions_PromotionId" FOREIGN KEY ("PromotionId") REFERENCES "Promotions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE TABLE "BookingPassengers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "BookingId" integer NOT NULL,
        "FullName" character varying(255) NOT NULL,
        "Gender" character varying(10),
        "DateOfBirth" timestamp with time zone,
        "NationalId" character varying(50),
        "PassengerType" integer NOT NULL DEFAULT 0,
        "FlightSeatInventoryId" integer NOT NULL,
        "FareSnapshot" text,
        CONSTRAINT "PK_BookingPassengers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_BookingPassengers_Bookings_BookingId" FOREIGN KEY ("BookingId") REFERENCES "Bookings" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_BookingPassengers_FlightSeatInventories_FlightSeatInventory~" FOREIGN KEY ("FlightSeatInventoryId") REFERENCES "FlightSeatInventories" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE TABLE "RefundRequests" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "BookingId" integer NOT NULL,
        "PaymentId" integer NOT NULL,
        "RefundAmount" numeric(10,2) NOT NULL,
        "Reason" character varying(500),
        "Status" integer NOT NULL DEFAULT 0,
        "ProcessedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_RefundRequests" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RefundRequests_Bookings_BookingId" FOREIGN KEY ("BookingId") REFERENCES "Bookings" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_RefundRequests_Payments_PaymentId" FOREIGN KEY ("PaymentId") REFERENCES "Payments" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE TABLE "BookingServices" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "BookingPassengerId" integer NOT NULL,
        "ServiceType" character varying(50) NOT NULL,
        "ServiceName" character varying(255) NOT NULL,
        "Price" numeric(10,2) NOT NULL,
        CONSTRAINT "PK_BookingServices" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_BookingServices_BookingPassengers_BookingPassengerId" FOREIGN KEY ("BookingPassengerId") REFERENCES "BookingPassengers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE TABLE "Tickets" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "BookingPassengerId" integer NOT NULL,
        "TicketNumber" character varying(50) NOT NULL,
        "Status" integer NOT NULL DEFAULT 0,
        "IssuedAt" timestamp with time zone NOT NULL,
        "ReplacedByTicketId" integer,
        CONSTRAINT "PK_Tickets" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Tickets_BookingPassengers_BookingPassengerId" FOREIGN KEY ("BookingPassengerId") REFERENCES "BookingPassengers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Tickets_Tickets_ReplacedByTicketId" FOREIGN KEY ("ReplacedByTicketId") REFERENCES "Tickets" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Aircraft_RegistrationNumber" ON "Aircraft" ("RegistrationNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_AircraftSeatTemplates_AircraftId_SeatClassId" ON "AircraftSeatTemplates" ("AircraftId", "SeatClassId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE INDEX "IX_AircraftSeatTemplates_SeatClassId" ON "AircraftSeatTemplates" ("SeatClassId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Airports_Code" ON "Airports" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE INDEX "IX_AuditLogs_ActorId" ON "AuditLogs" ("ActorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE INDEX "IX_BookingPassengers_BookingId" ON "BookingPassengers" ("BookingId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE INDEX "IX_BookingPassengers_FlightSeatInventoryId" ON "BookingPassengers" ("FlightSeatInventoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Bookings_BookingCode" ON "Bookings" ("BookingCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE INDEX "IX_Bookings_OutboundFlightId" ON "Bookings" ("OutboundFlightId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE INDEX "IX_Bookings_PromotionId" ON "Bookings" ("PromotionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE INDEX "IX_Bookings_ReturnFlightId" ON "Bookings" ("ReturnFlightId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE INDEX "IX_Bookings_UserId" ON "Bookings" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE INDEX "IX_BookingServices_BookingPassengerId" ON "BookingServices" ("BookingPassengerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE INDEX "IX_EmailVerificationTokens_UserId" ON "EmailVerificationTokens" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE INDEX "IX_Flights_AircraftId" ON "Flights" ("AircraftId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Flights_FlightNumber" ON "Flights" ("FlightNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE INDEX "IX_Flights_RouteId" ON "Flights" ("RouteId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_FlightSeatInventories_FlightId_SeatClassId" ON "FlightSeatInventories" ("FlightId", "SeatClassId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE INDEX "IX_FlightSeatInventories_SeatClassId" ON "FlightSeatInventories" ("SeatClassId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE INDEX "IX_NotificationLogs_UserId" ON "NotificationLogs" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE INDEX "IX_PasswordResetTokens_UserId" ON "PasswordResetTokens" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Payments_BookingId" ON "Payments" ("BookingId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Promotions_Code" ON "Promotions" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE INDEX "IX_PromotionUsages_BookingId" ON "PromotionUsages" ("BookingId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_PromotionUsages_PromotionId_BookingId" ON "PromotionUsages" ("PromotionId", "BookingId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE INDEX "IX_RefundPolicies_SeatClassId" ON "RefundPolicies" ("SeatClassId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE INDEX "IX_RefundRequests_BookingId" ON "RefundRequests" ("BookingId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_RefundRequests_PaymentId" ON "RefundRequests" ("PaymentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Roles_Name" ON "Roles" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE INDEX "IX_RoleUser_UsersId" ON "RoleUser" ("UsersId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE INDEX "IX_Routes_ArrivalAirportId" ON "Routes" ("ArrivalAirportId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE INDEX "IX_Routes_DepartureAirportId" ON "Routes" ("DepartureAirportId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_SeatClasses_Code" ON "SeatClasses" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Tickets_BookingPassengerId" ON "Tickets" ("BookingPassengerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE INDEX "IX_Tickets_ReplacedByTicketId" ON "Tickets" ("ReplacedByTicketId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Tickets_TicketNumber" ON "Tickets" ("TicketNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE INDEX "IX_UserRoles_RoleId" ON "UserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Users_GoogleId" ON "Users" ("GoogleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413135213_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260413135213_InitialCreate', '10.0.5');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416202008_AddCheckConstraintsToAllEntities') THEN
    ALTER TABLE "SeatClasses" ADD CONSTRAINT "CK_SeatClass_ChangeFee_NonNegative" CHECK ("ChangeFee" >= 0);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416202008_AddCheckConstraintsToAllEntities') THEN
    ALTER TABLE "SeatClasses" ADD CONSTRAINT "CK_SeatClass_RefundPercent_Valid" CHECK ("RefundPercent" >= 0 AND "RefundPercent" <= 100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416202008_AddCheckConstraintsToAllEntities') THEN
    ALTER TABLE "Routes" ADD CONSTRAINT "CK_Route_DifferentAirports" CHECK ("DepartureAirportId" != "ArrivalAirportId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416202008_AddCheckConstraintsToAllEntities') THEN
    ALTER TABLE "Routes" ADD CONSTRAINT "CK_Route_DistanceKm_Positive" CHECK ("DistanceKm" > 0);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416202008_AddCheckConstraintsToAllEntities') THEN
    ALTER TABLE "Routes" ADD CONSTRAINT "CK_Route_EstimatedDurationMinutes_Positive" CHECK ("EstimatedDurationMinutes" > 0);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416202008_AddCheckConstraintsToAllEntities') THEN
    ALTER TABLE "RefundRequests" ADD CONSTRAINT "CK_RefundRequest_RefundAmount_Positive" CHECK ("RefundAmount" > 0);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416202008_AddCheckConstraintsToAllEntities') THEN
    ALTER TABLE "RefundPolicies" ADD CONSTRAINT "CK_RefundPolicy_HoursBeforeDeparture_Positive" CHECK ("HoursBeforeDeparture" > 0);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416202008_AddCheckConstraintsToAllEntities') THEN
    ALTER TABLE "RefundPolicies" ADD CONSTRAINT "CK_RefundPolicy_PenaltyFee_NonNegative" CHECK ("PenaltyFee" >= 0);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416202008_AddCheckConstraintsToAllEntities') THEN
    ALTER TABLE "RefundPolicies" ADD CONSTRAINT "CK_RefundPolicy_RefundPercent_Valid" CHECK ("RefundPercent" >= 0 AND "RefundPercent" <= 100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416202008_AddCheckConstraintsToAllEntities') THEN
    ALTER TABLE "Promotions" ADD CONSTRAINT "CK_Promotion_DiscountValue_Positive" CHECK ("DiscountValue" > 0);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416202008_AddCheckConstraintsToAllEntities') THEN
    ALTER TABLE "Promotions" ADD CONSTRAINT "CK_Promotion_UsedCount_NonNegative" CHECK ("UsedCount" >= 0);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416202008_AddCheckConstraintsToAllEntities') THEN
    ALTER TABLE "Payments" ADD CONSTRAINT "CK_Payment_Amount_Positive" CHECK ("Amount" > 0);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416202008_AddCheckConstraintsToAllEntities') THEN
    ALTER TABLE "FlightSeatInventories" ADD CONSTRAINT "CK_FlightSeatInventory_AvailableSeats_Valid" CHECK ("AvailableSeats" >= 0 AND "AvailableSeats" <= "TotalSeats");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416202008_AddCheckConstraintsToAllEntities') THEN
    ALTER TABLE "FlightSeatInventories" ADD CONSTRAINT "CK_FlightSeatInventory_BasePrice_Positive" CHECK ("BasePrice" > 0);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416202008_AddCheckConstraintsToAllEntities') THEN
    ALTER TABLE "FlightSeatInventories" ADD CONSTRAINT "CK_FlightSeatInventory_CurrentPrice_Positive" CHECK ("CurrentPrice" > 0);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416202008_AddCheckConstraintsToAllEntities') THEN
    ALTER TABLE "FlightSeatInventories" ADD CONSTRAINT "CK_FlightSeatInventory_HeldSeats_NonNegative" CHECK ("HeldSeats" >= 0);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416202008_AddCheckConstraintsToAllEntities') THEN
    ALTER TABLE "FlightSeatInventories" ADD CONSTRAINT "CK_FlightSeatInventory_Seats_Total" CHECK ("AvailableSeats" + "HeldSeats" + "SoldSeats" <= "TotalSeats");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416202008_AddCheckConstraintsToAllEntities') THEN
    ALTER TABLE "FlightSeatInventories" ADD CONSTRAINT "CK_FlightSeatInventory_SoldSeats_NonNegative" CHECK ("SoldSeats" >= 0);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416202008_AddCheckConstraintsToAllEntities') THEN
    ALTER TABLE "FlightSeatInventories" ADD CONSTRAINT "CK_FlightSeatInventory_TotalSeats_Positive" CHECK ("TotalSeats" > 0);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416202008_AddCheckConstraintsToAllEntities') THEN
    ALTER TABLE "Bookings" ADD CONSTRAINT "CK_Booking_DiscountAmount_NonNegative" CHECK ("DiscountAmount" >= 0);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416202008_AddCheckConstraintsToAllEntities') THEN
    ALTER TABLE "Bookings" ADD CONSTRAINT "CK_Booking_FinalAmount_LessThanTotal" CHECK ("FinalAmount" <= "TotalAmount");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416202008_AddCheckConstraintsToAllEntities') THEN
    ALTER TABLE "Bookings" ADD CONSTRAINT "CK_Booking_FinalAmount_Positive" CHECK ("FinalAmount" > 0);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416202008_AddCheckConstraintsToAllEntities') THEN
    ALTER TABLE "Bookings" ADD CONSTRAINT "CK_Booking_TotalAmount_Positive" CHECK ("TotalAmount" > 0);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416202008_AddCheckConstraintsToAllEntities') THEN
    ALTER TABLE "AircraftSeatTemplates" ADD CONSTRAINT "CK_AircraftSeatTemplate_DefaultBasePrice_Positive" CHECK ("DefaultBasePrice" > 0);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416202008_AddCheckConstraintsToAllEntities') THEN
    ALTER TABLE "AircraftSeatTemplates" ADD CONSTRAINT "CK_AircraftSeatTemplate_DefaultSeatCount_Positive" CHECK ("DefaultSeatCount" > 0);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416202008_AddCheckConstraintsToAllEntities') THEN
    ALTER TABLE "Aircraft" ADD CONSTRAINT "CK_Aircraft_TotalSeats_Positive" CHECK ("TotalSeats" > 0);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260416202008_AddCheckConstraintsToAllEntities') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260416202008_AddCheckConstraintsToAllEntities', '10.0.5');
    END IF;
END $EF$;
COMMIT;

