BEGIN;

-- 1) Ensure EF migration history table exists
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

-- 2) Apply Payment status constraint for PendingRefund (status=5)
ALTER TABLE "Payments" DROP CONSTRAINT IF EXISTS "CK_Payment_Status_Valid";
ALTER TABLE "Payments"
ADD CONSTRAINT "CK_Payment_Status_Valid"
CHECK ("Status" IN (0, 1, 2, 3, 4, 5));

-- 2.1) Apply Booking status constraint for PartiallyCancelled (status=5)
ALTER TABLE "Bookings" DROP CONSTRAINT IF EXISTS "CK_Booking_Status_Valid";
ALTER TABLE "Bookings"
ADD CONSTRAINT "CK_Booking_Status_Valid"
CHECK ("Status" IN (0, 1, 2, 3, 4, 5));

-- 2.2) Allow multiple tickets per passenger (round-trip: outbound + return)
DROP INDEX IF EXISTS "IX_Tickets_BookingPassengerId";
CREATE INDEX IF NOT EXISTS "IX_Tickets_BookingPassengerId"
    ON "Tickets" ("BookingPassengerId");

-- 2.3) Allow multiple refund requests for a payment (partial ticket cancellations)
DROP INDEX IF EXISTS "IX_RefundRequests_PaymentId";
CREATE INDEX IF NOT EXISTS "IX_RefundRequests_PaymentId"
    ON "RefundRequests" ("PaymentId");

-- 3) Create SavedPassengers table (additive only)
CREATE TABLE IF NOT EXISTS "SavedPassengers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "FirstName" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "DateOfBirth" timestamp with time zone NULL,
    "Gender" character varying(20) NULL,
    "Nationality" character varying(100) NULL,
    "DocumentNumber" character varying(50) NULL,
    "Email" character varying(255) NOT NULL,
    "Phone" character varying(20) NULL,
    "IsDefaultOwner" boolean NOT NULL DEFAULT FALSE,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL DEFAULT FALSE,
    "DeletedAt" timestamp with time zone NULL,
    "Version" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_SavedPassengers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SavedPassengers_Users_UserId"
        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_SavedPassengers_UserId"
    ON "SavedPassengers" ("UserId");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_SavedPassengers_UserId_IsDefaultOwner"
    ON "SavedPassengers" ("UserId", "IsDefaultOwner")
    WHERE "IsDefaultOwner" = true AND "IsDeleted" = false;

-- 4) Mark migrations as applied so EF doesn't try to replay initial schema creation
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260507174307_Initial_Fix_Syntax', '10.0.5')
ON CONFLICT ("MigrationId") DO NOTHING;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260518120000_UpdatePaymentStatusConstraintForPendingRefund', '10.0.5')
ON CONFLICT ("MigrationId") DO NOTHING;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260518104500_AddSavedPassengers', '10.0.5')
ON CONFLICT ("MigrationId") DO NOTHING;

COMMIT;
